import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { MapContainer, TileLayer, Marker, Popup } from "react-leaflet";

export default function Home() {
  const [search, setSearchQuery] = useState("");

  const findLocation = (e) => {
    e.preventDefault();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Find your location</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.head}>
        <h1>IP Address Tracker</h1>

        <div className={styles.inputContainer}>
          <form onSubmit={findLocation}>
            <input
              type="text"
              placeholder="Search for any IP address or domain"
              value={search}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </form>
        </div>
        <div className={styles.locationDetails}>
          <div className={location.details}>
            <h5>IP ADDRESS</h5>
            <h1>192.212.174.101</h1>
          </div>
          <div className={location.details}>
            <h5>LOCATION</h5>
            <h1>Brooklyn, NY, 10001</h1>
          </div>
          <div className={location.details}>
            <h5>TIMEZONE</h5>
            <h1>UTC-5:00</h1>
          </div>
          <div className={location.details}>
            <h5>ISP</h5>
            <h1>SPACEX STARLINK</h1>
          </div>
        </div>
      </div>
      <div className={styles.mapContainer}>
        <MapContainer
          center={[51.505, -0.09]}
          zoom={13}
          scrollWheelZoom={false}
        >
          <TileLayer
            attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          />
          <Marker position={[51.505, -0.09]}>
            <Popup>
              A pretty CSS3 popup. <br /> Easily customizable.
            </Popup>
          </Marker>
        </MapContainer>
      </div>
    </div>
  );
}
